### PR TITLE
Added support for the Raspberry Pi Zero W and possibly other armv61 based Rasperry Pis

### PR DESCRIPTION
**Pull request by thaasoph**
On the Raspberry Pi Zero W and possibly other devices with an armv61 architecture the installation from the Debian repo won't work because the version is not compiled for this architecture.
It is required to manually compile WireGuard from its source to install it.

### CODE REVIEW

**Comment by mawalu** [comment]
Oh wow, that sounds interesting. How long does this take to run on a Pi Zero?

I'm happy to merge this but I think compiling stuff and rebooting the device could be unexpected for people running the role. What do you think of adding a flag / variable for this? Similar to how people need to opt-in to backports being enabled even though they are required for the role to work.

**Comment by thaasoph** [comment]
It does take some time but not forever. Maybe 15-20 minutes total? I hope my guess isn't too far off, I was doing other things while it ran and didn't stop it. I can do so tomorrow and give a hint in the documentation about how long it'll take.

Yes, rebooting the Pi could be unexpected. I didn't think about that. Personally, I would add a task that detects the architecture that requires a manual build and perform an assert on the opt-in flag. If it is not set, I'd fail on purpose for the host in question.

There are more things that bother me.
For the manual build, I need to clone the sources. As of right now I'm doing that into /tmp because of simplicity. Unfortunately that is bad practice because I makes the playbook less idempotent. Right now the cloned sources get deleted on every boot which is incidentally right before I need them. Do you have a good idea where I could put them? This would also help to reduce the runtime of the playbook sinificantly.

**Comment by mawalu** [comment]
Yes cloning the repo on every run seems less then perfect. I'm not perfectly sure ether where to put the files instead, maybe `/opt` or `/var/cache` because caching the files is really what we do here? Independent of our choice we could make it configurable.

While thinking about this I also noticed something else. Does the role recompile and reinstall wireguard on every run? It doesn't seem to check if the module and tools are already present and up to date.

**Comment by thaasoph** [comment]
Ok, I added the possibility to override the path at which the sources are cloned and it defaults to `/var/cache`.
I also added the flag to "accept" the build from source as well as the required reboots.

The `make` module is idempotent'ish. Which means if the compiled sources are already present, it won't do anything and won't detect a change. However, I have some issue with the WireGuard build because at least some of the targets are `PHONY`, which means there is no way for `make` to actually detect whether the target has to be remade and it just always remakes them and always detects a change. That only takes a few seconds but is irritating nonetheless. 
Besides checking for the existence of compiled files I don't have a solution to check whether this step has to be done again.

I have to admit that this is actually the first project with ansible am actually working on so there is a good chance there is an obvious solution that I don't know of. 

Other than that I think I have fixed everything. I have flashed my Zero W at least a dozen times this evening until everything worked. Poor thing. 🙈

**Comment by mawalu** [comment]
Ah I totally missed that the `make` call invokes an additional role. Overall I think this looks really nice, I will do a bit of testing (hopefully today) but everything looks promising.

Last think to ask is if you could add an addition section to the readme with some infos. The flag alone doesn't realy make it clear that this enables the role to runs on the pi zero and also the dependency on `community.general` isn't document. Something along the line of

```
# Raspberry Pi Zero support
needs kernel headers and manual compilation of wireguard, opt in via flag, install `community.general` role
```

Thanks for all the effort contributing this :)

**Pull request merged**
