### PR TITLE
Client peer

### PR DESCRIPTION
**Pull request by bilenkis**
This PR adds config generation for host from where I'm running your role (e.g. client peer). It allows you to connect to each node from your local machine.

Tested with OS X.

### CODE REVIEW

**Comment by mawalu** [comment]
Hi and thanks for the contribution. I did a test on my machine and everything seems to work fine, I just have a few comments before merging:

* Is the `client_cfg.txt.j2` file used anywhere? I think its just a leftover copy
* You changed `inventory_hostname` to `ansible_host` and this breaks my setup since ansible can't read that value for my hosts. Would you mind giving an example inventory so I can check what difference could cause this problem. From everything I've read `ansible_host` seems to be the better value here. 
* Could you please mention the new variables in the README file so they are better documented

**Comment by bilenkis** [comment]
Hi, I'm glad to be part of this open source project. I commited some changes as you asked me.
+ the file client_cfg.txt.j2 was removed
+ I added *inventory_hostname* as a default variable in cases when *ansible_host* is not defined. Your playbook won't fail now.
Some explanations about inventory file. In all best practices I saw there is an inventory file like this:
```yaml
wireguard:
  hosts:
    node1:
      ansible_host: 1.1.1.1
      vpn_ip: 10.1.0.1/32
    node2:
      ansible_host: 2.2.2.2
      vpn_ip: 10.1.0.2/32
```
In this case *ansible_host* used as an endpoint to connect to. In the same time your inventory file became more human readable. You can see the name of your host and the ability to connect to it.
+ I decided that it is not necessary to use two variables. So I removed *generate_client_config* variable. Playbook uses only *client_wireguard_path* now to define whether generate client config or not.

**Comment by mawalu** [comment]
Looks good to me now :+1:

Thanks for your contribution.

**Comment by bilenkis** [comment]
Wow, blazingly fast, thanks! Can you please update your role on ansible-galaxy.

**Comment by mawalu** [comment]
I tagged a v1 release and pushed it to ansible-galaxy

**Pull request merged**
